-- ============================================================
-- Seed data cơ bản — chỉ chứa những gì DataInitializer không xử lý
-- Dữ liệu mẫu (categories, shops, products) được tạo tự động
-- bởi DataInitializer.java khi ứng dụng khởi động lần đầu
-- ============================================================
