-- ============================================================
-- Basic seed data placeholder.
-- Demo categories and products are created by DataInitializer.java
-- when the application starts with an empty database.
-- ============================================================
